config_vars = {
    'project_id': [ENTER YOUR PROJECT ID HERE],
    'API_KEY': '[ENTER YOUR API KEY HERE]'
    'API_KEY_SECRET': '[ENTER YOUR SECRET API KEY HERE]'
    'ACCESS_TOKEN': '[ENTER YOUR ACCESS TOKEN HERE]'
    'ACCESS_TOKEN_SECRET': '[ENTER YOUR SECRET ACCESS TOKEN HERE]'
    'py_file_path': 'body.py'
}
